### ISSUE TITLE
Just don't work

### ISSUE THREAD

**Issue by Lejo1** [appgurueu/punchback#1]
Pos never gets set to a new value.

**Comment by appgurueu** [comment]
```pos=vector.add(pos,mult)
end
::overjump::
player:moveto(pos) --Actual punchback```

Ermm-you are wrong
Anyway, I have understood it is a bad idea to use gotos, as they aren't that easy to understand...

**Comment by Lejo1** [comment]
I know that you use moveto, but pos is always the pos where the player already is!
https://s33.postimg.cc/ugo4w8eyn/output_p3n_O1_P.gif

**Comment by Lejo1** [comment]
@appgurueu

**Comment by amadin** [comment]
I confirm this bug
0.4.17.1

**Comment by appgurueu** [comment]
Sorry, my if uses wrong condition... Should be fixed now... Will test it...
